# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9545f4550360d082b0799cfc11db54ffb7df51901586ed97adcabf9fa268e69c770dd9fcc2bb4c984cd98bef328c2d9df7d64bd21890d1f31dbec3cf77e0a2b3

test:
  secret_key_base: 78814cfbfdb78c69929f90f3620e2aff0b092186403841f267ec28c241b8c11b9b96fe06cd6032d63d1d7f2e84e412db853f6b3de100ecab346453e21ae94a81

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
